# -*- coding: utf-8 -*-
"""PI 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SoTf19EgVk-L2Te1jlBynU5vv8FO2Ill
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Puxando a base
dados = pd.read_csv('base_de_dados_p3.csv')

# Ajuste de data

dados['data'] = pd.to_datetime(dados['data'])

# Agrupamento da data

dados_diarios = (
    dados.groupby('data')['preco_venda']
    .mean()
    .reset_index()
)

# Valores estatísticos

media_preco = dados_diarios['preco_venda'].mean()

mediana_preco = dados_diarios['preco_venda'].median()

desvio_padrao = dados_diarios['preco_venda'].std()

print('\n========== ESTATÍSTICAS ==========')

print(f'Ticket Médio: {media_preco:.2f}')

print(f'Mediana: {mediana_preco:.2f}')

print(f'Desvio Padrão: {desvio_padrao:.2f}')

# encontrando os outliers (mede o intervalo interquartil)

Q1 = dados_diarios['preco_venda'].quantile(0.25)

Q3 = dados_diarios['preco_venda'].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR

limite_superior = Q3 + 1.5 * IQR

# identificando os outliers para o filtro

outliers = dados_diarios[
    (dados_diarios['preco_venda'] < limite_inferior) |
    (dados_diarios['preco_venda'] > limite_superior)
]

print('\n========== OUTLIERS IDENTIFICADOS ==========')

print(outliers)

# remoção dos outliers

dados_sem_outliers = dados_diarios[
    (dados_diarios['preco_venda'] >= limite_inferior) &
    (dados_diarios['preco_venda'] <= limite_superior)
]

print('\n========== DADOS SEM OUTLIERS ==========')

print(dados_sem_outliers.head())

# gráfico

plt.figure(figsize=(14,7))

# dados originais

plt.plot(
    dados_diarios['data'],
    dados_diarios['preco_venda'],
    label='Dados Originais',
    linewidth=2
)

# dados sem os outliers

plt.plot(
    dados_sem_outliers['data'],
    dados_sem_outliers['preco_venda'],
    label='Dados Sem Outliers',
    linewidth=2
)


# média

plt.axhline(
    media_preco,
    linestyle='--',
    label=f'Média: {media_preco:.2f}'
)

# mediana

plt.axhline(
    mediana_preco,
    linestyle=':',
    label=f'Mediana: {mediana_preco:.2f}'
)

plt.title('Análise Estatística dos Dados')

plt.xlabel('Data')

plt.ylabel('Preço Médio')

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from sklearn.linear_model import LinearRegression

# colocando o arquivo

dados = pd.read_csv('base_de_dados_p3.csv')

# ajustando a data

dados['data'] = pd.to_datetime(dados['data'])

# =agrupamento por dia

dados_diarios = (
    dados.groupby('data')['preco_venda']
    .mean()
    .reset_index()
)

# retirando os outliers

Q1 = dados_diarios['preco_venda'].quantile(0.25)

Q3 = dados_diarios['preco_venda'].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR

limite_superior = Q3 + 1.5 * IQR

dados_limpos = dados_diarios[
    (dados_diarios['preco_venda'] >= limite_inferior) &
    (dados_diarios['preco_venda'] <= limite_superior)
].copy()

# agrupamento semanal

dados_semanais = (
    dados_limpos
    .set_index('data')
    .resample('W')['preco_venda']
    .mean()
    .reset_index()
)

# ajustando as variaveis de tempo

dados_semanais['semanas'] = np.arange(len(dados_semanais))

x = dados_semanais[['semanas']]

y = dados_semanais['preco_venda']

# treinando o modelo

modelo = LinearRegression()

modelo.fit(x, y)

# previsão proximas 8 semanas

futuras_semanas = np.arange(
    len(dados_semanais),
    len(dados_semanais) + 8
).reshape(-1, 1)

previsoes = modelo.predict(futuras_semanas)

previsoes = np.round(previsoes, 2)

# datas futuras

ultima_data = dados_semanais['data'].max()

datas_futuras = pd.date_range(
    start=ultima_data + pd.Timedelta(weeks=1),
    periods=8,
    freq='W'
)

# resultado

resultado_previsao = pd.DataFrame({

    'Semana': datas_futuras,

    'Preço Previsto': previsoes

})

print('\n========== PREVISÃO SEMANAL ==========')

print(resultado_previsao)

# gráfico

plt.figure(figsize=(16,8))

# histórico

plt.plot(
    dados_semanais['data'],
    dados_semanais['preco_venda'],
    linewidth=3,
    label='Histórico Semanal'
)

# previsão

plt.plot(
    datas_futuras,
    previsoes,
    '--',
    linewidth=3,
    label='Previsão Próximas 8 Semanas'
)

# sombreado

plt.fill_between(
    datas_futuras,
    previsoes,
    alpha=0.2
)

# formatação das datas

ax = plt.gca()

ax.xaxis.set_major_formatter(
    mdates.DateFormatter('%d/%m/%Y')
)

# títulos

plt.title(
    'Previsão Semanal Sem Outliers',
    fontsize=18
)

plt.xlabel(
    'Semana',
    fontsize=12
)

plt.ylabel(
    'Preço Médio',
    fontsize=12
)

plt.legend()

plt.grid(True)

plt.xticks(rotation=30)

plt.tight_layout()

plt.show()

#@title Subindo e verificando as colunas

print(dados.columns)

import pandas as pd
dados = pd.read_csv('base_de_dados_p3.csv')
print(dados.head())